baseURL = "https://ostanikodkuce.rs/"
languageCode = "rs"
title = "Ostani kod kuće - COVID-19"
theme = "anubis"

[params]
  description = "Saznaj više šta možeš samostalno da uradiš kako bi sprečio dalje širenje COVID-19"
  title = "Ostani kod kuće - COVID-19"
  images = ["static/meta.jpg"]

[taxonomies]
  series = "series"