baseURL = "https://ostanikodkuce.rs/"
languageCode = "rs"
title = "ostanikodkuce.rs"
theme = "anubis"

[params]
  description = "Saznaj više šta možeš samostalno da uradiš kako bi sprečio dalje širenje COVID-19"
  title = "ostanikodkuce.rs"

[taxonomies]
  series = "series"