baseURL = "https://ostanikodkuce.rs/"
languageCode = "lt"
title = "Pasilik namie - COVID-19"
theme = "anubis"

[params]
  description = "Sužinokite daugiau apie tai, ką galite padaryti, kad COVID-19 neplistų toliau"
  title = "Pasilik namie - COVID-19"
  images = ["meta.jpg"]

[taxonomies]
  series = "series"
