baseURL = "https://pasiliknamie.lt/"
languageCode = "lt"
title = "#pasiliknamie"
theme = "anubis"

[params]
  description = "Sužinokite daugiau apie tai, ką galite padaryti, kad COVID-19 neplistų toliau"
  title = "Pasilik namie - COVID-19"
  images = ["meta.jpg"]

[taxonomies]
  series = "series"
